pipeline:
  name: sample-react-app
  identifier: samplereactapp
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build test and run
        identifier: build_test_and_run
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: install node modules
                  identifier: install_node_modules
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build and push to docker
                  identifier: build_and_push_to_docker
                  spec:
                    connectorRef: harnesscommunitydocker
                    repo: harnesscommunity/python-test
                    tags:
                      - latest
                    dockerfile: Dockerfile
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sdelegate
              namespace: harness-delegate-ng
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: sample-react-app-ci
        build: <+input>
